// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8FSEL_xBz1R5VAzdrJJO_LfQZJHHcvCU',
    appId: '1:97830148229:web:de1e35fac7dc3db27931ec',
    messagingSenderId: '97830148229',
    projectId: 'redditclone-fdb06',
    authDomain: 'redditclone-fdb06.firebaseapp.com',
    storageBucket: 'redditclone-fdb06.appspot.com',
    measurementId: 'G-4MS75CTSLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIJ-kauEaPlNr4B-f3gFKlCG3FN_hk83I',
    appId: '1:97830148229:android:4fc75941fef964277931ec',
    messagingSenderId: '97830148229',
    projectId: 'redditclone-fdb06',
    storageBucket: 'redditclone-fdb06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZO0qDv8i9YjnTZ5scrjfSLkpIFC1pDMM',
    appId: '1:97830148229:ios:94415b94675427c37931ec',
    messagingSenderId: '97830148229',
    projectId: 'redditclone-fdb06',
    storageBucket: 'redditclone-fdb06.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZO0qDv8i9YjnTZ5scrjfSLkpIFC1pDMM',
    appId: '1:97830148229:ios:85e2a3fa2fa9e3887931ec',
    messagingSenderId: '97830148229',
    projectId: 'redditclone-fdb06',
    storageBucket: 'redditclone-fdb06.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
